GET http://localhost:3000/categories

###
GET http://localhost:3000/categories/2

###
GET http://localhost:3000/categories/7

###
GET http://localhost:3000/categories/8

###

POST http://localhost:3000/categories/
Content-Type: application/json

{
  "name": "Art"
}

###

DELETE http://localhost:3000/categories/1


https://ticktick.com/oauth/authorize?scope=tasks:write tasks:read&client_id=2D6Mc3Rsy7s4SBPcg3&state=state&redirect_uri=https://api.mateuszniestroj.pl/auth&response_type=code
