@hostname = localhost
@port = 3000
@host = {{hostname}}:{{port}}
@contentType = application/json


### [C]reate new product:
POST http://@{{host}}/products
Content-Type: application/json

{
  "name": "Kubek",
  "price": 18.25,
  "description": "Napij się prosto z Cuba",
  "image": "https://picsum.photos/id/30/1280/901",
  "stock": 10
}

### [R]ead products:
GET http://@{{host}}/products

### [R]ead product:
GET http://@{{host}}/products/2

### [R]ead product - not existed:
GET http://@{{host}}/products/100

### [R]ead product - wrong parameter:
GET http://@{{host}}/products/something

### [U]pdate product
PATCH http://@{{host}}/products/2
Content-Type: application/json

{
  "description": "100% Porcelana"
}

### [D]elete product
DELETE http://@{{host}}/products/1


### Search products by name:
GET http://localhost:3000/products?name=atu
